name: "TVmaze"
guid: "A4A488D0-17A3-4919-8D82-7F3DE4F6B209"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-tvmaze.png"
version: 14
targetAbi: "10.11.5.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Get TV metadata from TVmaze"
description: >
  Get TV metadata from TVmaze

category: "MoviesAndShows"
artifacts:
  - "Jellyfin.Plugin.TvMaze.dll"
  - "TvMaze.Api.Client.dll"
  - "Flurl.dll"
  - "Flurl.Http.dll"
  - "Polly.dll"
changelog: |-
  - Revert "Update dependency Microsoft.Extensions.Http to v10" (#62) @Shadowghost

  ### Dependency updates ###
  - Update dependency Microsoft.Extensions.Http to 9.0.11 (#52) @[renovate[bot]](https://github.com/apps/renovate)
  - Update dependency Microsoft.Extensions.Http to v10 (#59) @[renovate[bot]](https://github.com/apps/renovate)
