name: "TVmaze"
guid: "A4A488D0-17A3-4919-8D82-7F3DE4F6B209"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-tvmaze.png"
version: 12
targetAbi: "10.10.6.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Get TV metadata from TVmaze"
description: >
  Get TV metadata from TVmaze

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.TvMaze.dll"
  - "TvMaze.Api.Client.dll"
  - "Flurl.dll"
  - "Flurl.Http.dll"
  - "Polly.dll"
changelog: |-
  - Fallback on empty ParentIndexNumber (#54) @Shadowghost
  - Should provide identifying info in its exception (#47) @michaelkrieger
  - Add basic handling for specials (#23) @Smith00101010
